name: dak
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  supabase_flutter: ^2.5.5
  provider: ^6.1.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/d_logo.jpg
    - assets/logo_d_icon_v2.jpg
    - assets/onboarding_1.jpg
    - assets/onboarding_2.jpg
    - assets/onboarding_screen_1.png
    - assets/onboarding_screen_2.png
    - assets/onboarding_screen_3.png
    - assets/onboarding_screen_4.png
    - assets/onboarding_illus_1.png
    - assets/onboarding_illus_2.png
    - assets/onboarding_illus_3.png
    - assets/onboarding_illus_4.png
    - assets/rocket.png
